# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ur_joint_trajectory_controller
    - axis_joint_trajectory_controller

  ur_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  axis_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - axis_joint1
    action_ns: follow_joint_trajectory
    default: true