# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    axis_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_joint_trajectory_controller:
  ros__parameters:
    joints:
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []
axis_joint_trajectory_controller:
  ros__parameters:
    joints:
      - axis_joint1
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []