/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3
        solve_type: Manipulation2
