controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    

    axis_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    axis_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController




    forward_position_controller:
      type: position_controllers/JointGroupPositionController


speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "UR_"

io_and_status_controller:
  ros__parameters:
    tf_prefix: "UR_"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: UR_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: UR_tool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - axis_joint1
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    # constraints:
    #   stopped_velocity_tolerance: 0.2
    #   goal_time: 0.0
    #   axis_joint1: { trajectory: 0.2, goal: 0.1 }
    #   UR_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
    #   UR_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
    #   UR_elbow_joint: { trajectory: 0.2, goal: 0.1 }
    #   UR_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
    #   UR_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
    #   UR_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

ur_joint_trajectory_controller:
  ros__parameters:
    joints:
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      UR_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      UR_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      UR_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      UR_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      UR_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      UR_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

axis_joint_trajectory_controller:
  ros__parameters:
    joints:
      - axis_joint1
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      # stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      # axis_joint1: { trajectory: 0.2, goal: 0.1 }




forward_position_controller:
  ros__parameters:
    joints:
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint


forward_velocity_controller:
  ros__parameters:
    joints:
      - axis_joint1
      - UR_shoulder_pan_joint
      - UR_shoulder_lift_joint
      - UR_elbow_joint
      - UR_wrist_1_joint
      - UR_wrist_2_joint
      - UR_wrist_3_joint
    interface_name: velocity


axis_forward_velocity_controller:
  ros__parameters:
    joints:
      - axis_joint1
    interface_name: velocity