publisher_forward_velocity_controller:
  ros__parameters:

    controller_name: "axis_forward_velocity_controller"
    wait_sec_between_publish: 1
    goal_names: ["pos1", "pos2", "pos3"]
    pos1: [0.10]
    pos2: [-0.10]
    pos3: [0.0]

