publisher_AAHAH_forward_velocity_controller:
  ros__parameters:

    controller_name: "forward_velocity_controller"
    wait_sec_between_publish: 1
    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.02,0.1, 0.0, 0.0, 0.0, 0.0, 0.05]
    pos2: [0.0,0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos3: [-.02,-0.1, 0.0, 0.0, 0.0, 0.0, -0.05]
    pos4: [0.0,0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


