
publisher_urjoint_trajectory_controller:
  ros__parameters:

    controller_name: "ur_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
    pos3:
      positions: [0.0, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]

    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    check_starting_point: false
