publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "scaled_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
    pos3:
      positions: [0.0, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]

    joints:
      - $(var ur_prefix)shoulder_pan_joint
      - $(var ur_prefix)shoulder_lift_joint
      - $(var ur_prefix)elbow_joint
      - $(var ur_prefix)wrist_1_joint
      - $(var ur_prefix)wrist_2_joint
      - $(var ur_prefix)wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      $(var ur_prefix)shoulder_pan_joint: [-3.0,3.1]
      $(var ur_prefix)shoulder_lift_joint: [-3.6,3.5]
      $(var ur_prefix)elbow_joint: [3.6,3.6]
      $(var ur_prefix)wrist_1_joint: [-3.6,3.5]
      $(var ur_prefix)wrist_2_joint: [-3.6,3.6]
      $(var ur_prefix)wrist_3_joint: [-3.1,3.61]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
    pos3:
      positions: [0.0, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]

    joints:
      - $(var ur_prefix)shoulder_pan_joint
      - $(var ur_prefix)shoulder_lift_joint
      - $(var ur_prefix)elbow_joint
      - $(var ur_prefix)wrist_1_joint
      - $(var ur_prefix)wrist_2_joint
      - $(var ur_prefix)wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      $(var ur_prefix)shoulder_pan_joint: [-3.0,3.1]
      $(var ur_prefix)shoulder_lift_joint: [-3.6,3.5]
      $(var ur_prefix)elbow_joint: [-3.6,3.6]
      $(var ur_prefix)wrist_1_joint: [-3.6,3.5]
      $(var ur_prefix)wrist_2_joint: [-3.6,3.6]
      $(var ur_prefix)wrist_3_joint: [-3.1,3.61]