controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController


speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "$(var tf_prefix)"

io_and_status_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: $(var tf_prefix)tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: $(var tf_prefix)tool0
    topic_name: ft_data


ur_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    gains:
      $(var tf_prefix)shoulder_pan_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)shoulder_lift_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)elbow_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)wrist_1_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)wrist_2_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)wrist_3_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0

ur_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    gains:
      $(var tf_prefix)shoulder_pan_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)shoulder_lift_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)elbow_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)wrist_1_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)wrist_2_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      $(var tf_prefix)wrist_3_joint:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 1.0


scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)elbow_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

forward_velocity_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
